parallel test

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -38,42 +38,42 @@ jobs:
           TO_EMAIL: ${{ secrets.TO_EMAIL }}
 
   test:
-    needs: lint
-    runs-on: windows-latest
-    strategy:
-      matrix:
-        node: [1, 2, 3]  # Runs 3 parallel jobs
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v4
+  needs: lint
+  runs-on: windows-latest
+  strategy:
+    matrix:
+      node: [1, 2, 3]  
+  steps:
+    - name: Checkout Code
+      uses: actions/checkout@v4
 
-      - name: Set up JDK 17
-        uses: actions/setup-java@v3
-        with:
-          distribution: temurin
-          java-version: '17'
+    - name: Set up JDK 17
+      uses: actions/setup-java@v3
+      with:
+        distribution: temurin
+        java-version: '17'
 
-      - name: Run Tests in Parallel with Knapsack-Pro
-        run: mvn test -Dknapsack.split=${{ matrix.node }}
+    - name: Run Tests in Parallel with Knapsack-Pro
+      run: mvn test "-Dknapsack.split=${{ matrix.node }}"
 
-      - name: Send Email on Failure
-        if: failure()
-        run: |
-          if (Test-Path ".\mailsend-go.exe") {
-            .\mailsend-go.exe -smtp $SMTP_SERVER -port $SMTP_PORT -auth -user $SMTP_USER -pass $SMTP_PASS `
-              -from $SMTP_USER -to $TO_EMAIL -sub "Test Failed in GitHub Actions" `
-              -M "The tests failed in GitHub Actions. Please check the logs."
-          } else {
-            echo "mailsend-go.exe not found!"
-            exit 1
-          }
-        shell: pwsh
-        env:
-          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
-          SMTP_PORT: ${{ secrets.SMTP_PORT }}
-          SMTP_USER: ${{ secrets.SMTP_USER }}
-          SMTP_PASS: ${{ secrets.SMTP_PASS }}
-          TO_EMAIL: ${{ secrets.TO_EMAIL }}
+    - name: Send Email on Failure
+      if: failure()
+      run: |
+        if (Test-Path ".\mailsend-go.exe") {
+          .\mailsend-go.exe -smtp $SMTP_SERVER -port $SMTP_PORT -auth -user $SMTP_USER -pass $SMTP_PASS `
+            -from $SMTP_USER -to $TO_EMAIL -sub "Test Failed in GitHub Actions" `
+            -M "The tests failed in GitHub Actions. Please check the logs."
+        } else {
+          echo "mailsend-go.exe not found!"
+          exit 1
+        }
+      shell: pwsh
+      env:
+        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
+        SMTP_PORT: ${{ secrets.SMTP_PORT }}
+        SMTP_USER: ${{ secrets.SMTP_USER }}
+        SMTP_PASS: ${{ secrets.SMTP_PASS }}
+        TO_EMAIL: ${{ secrets.TO_EMAIL }}
 
   deploy:
     needs: test
